services:
  # --- REVERSE PROXY (Nginx Proxy Manager) ---
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: sib-cr-proxy-prod
    restart: always
    ports:
      - "80:80"   # HTTP público
      - "443:443" # HTTPS público
      - "127.0.0.1:81:81"   # Panel de administración (Solo escucha peticiones internas tunel SSH)
    volumes:
      - ./proxy_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - sib-cr-network # <-- Le damos acceso a la red principal
      - sib-cr-monorepo_sib-cr-network-dev  # <-- Le damos acceso a la red de DEV

  # --- DATABASE --- #
  db:
    image: postgres:alpine
    container_name: sib-cr-database-prod
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: ${DATASOURCE_DB_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - sib_db_data:/var/lib/postgresql
    networks:
      - sib-cr-network

  # --- BACKEND --- #
  backend:
    image: lpcodeadmin/sib-backend:latest # <-- Tag :latest para producción
    container_name: sib-cr-backend-prod
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILES_ACTIVE:-prod}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATASOURCE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    env_file:
    - .env.prod
    depends_on:
      - db
    networks:
      - sib-cr-network

  # --- FRONTEND ADMIN REFINE--- #
  admin:
    image: lpcodeadmin/sib-frontend-admin:latest # <-- Tag :latest para producción
    container_name: sib_cr_frontend_admin_prod
    restart: always
    depends_on:
      - backend
    networks:
      - sib-cr-network

  # --- FRONTEND PUBLIC VITE--- #
  publico:
    image: lpcodeadmin/sib-frontend-publico:latest # <-- Tag :latest para producción
    container_name: sib_cr_frontend_publico_prod
    restart: always
    depends_on:
      - backend
    networks:
      - sib-cr-network

networks:
  sib-cr-network:
    driver: bridge
  sib-cr-monorepo_sib-cr-network-dev:
    external: true # Red creada y gestionada por docker-compose.dev.yml, solo la usamos aquí para conectar el proxy a los servicios de desarrollo

volumes:
  sib_db_data:
  proxy_data: